export const examsToSeed = [
  {
    examNumber: 1,
    title: "Igice cya 1",
    isFree: true,
    questions: [
      {
        text: "1. Iyo imirimo ikorwa mu muhanda icyapa cyerekana ikorwa ry'iyo mirimo kigomba kugira uruhande rufite:",
        options: [
          "A. Cm 50 z'uruhande",
          "B. Cm 40 z'uruhande",
          "C. Cm 55 z'uruhande",
          "D. M 1 y'uruhande",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "2. Ubugari bw'imizigo yikorewe n'ipikipiki ifite akanyabiziga kuruhande kimwe n'ubwa iya rumoruki ikuruwe na bene icyo kinyabiziga ntiburenza:",
        options: [
          "A. Ntagisubizo cy'ukuri kirimo",
          "B. Santamirero 75 : (igare)",
          "C. Metero 1,25 : (moto cg pikipiki)",
          "D. Metero 1,50",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "3. Iyo imizigo isumba impera y'inyuma y'ikinyabiziga ho metero irenga, igice gihera k'umuzigo kigomba kugaragazwa ku manywa:",
        options: [
          "A. N'agatambaro kera gafite cm 50 z'uruhande",
          "B. N'agatambaro gatukura gafite cm 59 z'uruhande",
          "C. Ntagisubizo cy'ukuri kirimo",
          "D. N'agatambaro gatukura gafite cm 50 z'uruhande",
        ],
        correctAnswerIndex: 3,
      },
      {
        text: "4. Ikinyabiziga gishyirwaho ikimenyetso cy’uko umuyobozi wacyo yabonye ikimenyetso cy’uwitegura kumunyuraho ni ikinyabiziga gikurikira:",
        options: [
          "A. Kirenza metero 8 z'uburebure",
          "B. Kirenza uburebure bwa metero 10",
          "C. Kirenza metero 2,10 z'ubugari",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "5. Abanyamaguru banyura mu butaka butsindagiye butandukanya imihanda iyo:",
        options: [
          "A. Nta tuyira to ku mpande z'umuhanda duhari",
          "B. A na B ni ibisubizo by'ukuri",
          "C. Nta nkengero yegutse ihari",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "6. Amatara ndanga mbere yakira rimwe buri gihe n'amatara akurikira:",
        options: [
          "A. Magufi na kamenabihu y'imbere",
          "B. Maremare",
          "C. Ndangamubyimba",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "7. Abayobozi b'amagare na velomoteri bubahiriza amategeko agenga abanyamaguru iyo:",
        options: [
          "A. Bagenda mukayira k'abanyamaguru",
          "B. Bayoboye ikinyabiziga cyabo batacyicayeho",
          "C. Bagenda ku nkengero yegutse",
          "D. A na B ni ibisubizo by'ukuri",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "8. Iyo umuhanda ugabanyijwemo ibisate bibiri kandi kuwugendamo bigakorwa mu byerekezo byombi, abayobozi babujijwe kugendera mu gisate cy'ibumoso:",
        options: [
          "A. Keretse kujya muri urwo ruhande byemewe",
          "B. N'iyo kujya muri urwo ruhande byemewe",
          "C. Keretse iyo ari umuhanda w'icyerekezo",
          "D. Nta gisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "9. Amatara maremare n'amagufi azima iyo:",
        options: [
          "A. Ikinyabiziga kigiye guhura n'ikindi",
          "B. Umuhanda umurikiwe hose",
          "C. Ikinyabiziga gihagaze",
          "D. Bishoboka kubona neza muri metero 100",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "10. Icyapa gitegeka gukikira gifite ubuso bw'ibara:",
        options: [
          "A. Ryera",
          "B. Ry'ubururu",
          "C. Ritukura",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "11. Gushyira mu muhanda ibinyabiziga bikururana birenze bitatu bitangirwa uruhushya na:",
        options: [
          "A. Minisitiri ushinzwe gutwara abantu n'ibintu",
          "B. Perefe",
          "C. Minisitiri w'imirimo ya leta",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "12. Ubugari bw'imizigo yikorewe n'igare na velomoteri kimwe na rumoruki zikuruwe nabyo ntiburenza:",
        options: [
          "A. Metero 1,25",
          "B. Metero 1",
          "C. Santimetero 75",
          "D. Metero 2,10",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "13. Umubare ntarengwa w'ibinyabiziga bikururana ni:",
        options: [
          "A. Bitatu",
          "B. Bibiri",
          "C. Bine",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "14. Icyapa cyerekana inzira y'amatungo itegetswe gifite ubuso bukurikira:",
        options: [
          "A. Bw'ubururu",
          "B. Bwera",
          "C. Bw'umuhondo",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "15. Umuvuduko ntarengwa w'ibinyabiziga bihinga {bifite imipira irambura cg utarambuka} bishobora kugeza k'ubugari bwa metero 3 ni:",
        options: [
          "A. Km 20 mu isaha",
          "B. Km 40 mu isaha",
          "C. Km 25 mu isaha",
          "D. Km 50 mu isaha",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "16. Ubugari bw'imizingo yikorewe n'ikinyabiziga bupimiwe mu butambike ubwo ari bwo bwose ntiburenza:",
        options: [
          "A. Metero 3",
          "B. Metero 2,50",
          "C. Metero 2,65",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "17. Umuvuduko ntarengwa w'ibinyabiziga bitwarira abantu hamwe mu nsisiro ni:",
        options: [
          "A. Km 50 mu isaha",
          "B. Km 60 mu isaha",
          "C. Km 40 mu isaha",
          "D. Km 75 mu isaha",
          "E. Km 70 mu isaha",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "18. Imburira zimurika zikoreshwa kuburyo bukurikira:",
        options: [
          "A. Bacana bazimya vubavuba amatara ndanga",
          "B. B na C ni ibisubizo by'ukuri",
          "C. Bacana bazimya vubavuba amatara magufi",
          "D. Basimburanya vuba vuba amatara magufi n'amatara maremare",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "19. Ubugari bwa rumoruki ikuruwe n'ipikipiki icometseho akanyabiziga ku ruhande rwayo cyangwa ikuruwe n'ikinyamitende 3 cyangwa 4 gifite cyangwa kidafite moteri ntiburenza:",
        options: [
          "A. Metero 1,25",
          "B. Santimetero 75",
          "C. Metero 1,50",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "20. Iyo kuva bwije kugeza bukeye bidashoboka kubona neza muri metero 200, rumoruki ikuruwe na velomoteri, ikinyamitende cyangwa ipikipiki idafite akanyabiziga kuruhande igomba kugaragazwa:",
        options: [
          "A. N'itara ry'umutuku",
          "B. N'itara ryera, ry'umuhondo cyangwa risa n'icunga",
          "C. N'itara ry'umuhondo",
          "D. N'itara rimyasa",
        ],
        correctAnswerIndex: 1,
      },
    ],
  },
  {
    examNumber: 2,
    title: "Igice cya 2",
    isFree: false,
    questions: [
      {
        text: "1. Iyo imirimo iri gukorwa mu muhanda icyapa kiyerekana kigomba kugira uruhande rufite:",
        options: [
          "A. Cm 40 z'uruhande",
          "B. Cm 50 z'uruhande",
          "C. Cm 70 z'uruhande",
          "D. Cm 90 z'uruhande",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "2. Uburebure ntarengwa bw’ibinyabiziga bikururana ni:",
        options: [
          "A. Metero 15",
          "B. Metero 20",
          "C. Metero 25",
          "D. Metero 10",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "3. Ibizirikisho by'iminyururu cyangwa by'insinga kimwe n'ibindi bizirikisho by'ingoboka bigaragazwa n'ikimenyetso gikurikira:",
        options: [
          "A. Igitambaro gitukura gifite cm 50 z'uruhande",
          "B. Icyapa cyera cya mpande enye gifite cm 30 z'uruhande",
          "C. Icyapa cyera cya mpande enye gifite cm 50 z'uruhande",
          "D. Icyapa cyera cya mpande eshatu gifite cm 30 z'uruhande",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "4. Itara ryo gusubira inyuma rigomba kohereza urumuri mu ntera ikurikira:",
        options: [
          "A. Metero 30",
          "B. Metero 20",
          "C. Metero 50",
          "D. Metero 150",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "5. Uretse iyo bitegetswe n'umukozi ubifitiye ububasha kandi batakwiteza ibyago, abayobozi b'ibinyabiziga ndakumirwa ntibategetswe gukurikiza amategeko akurikira:",
        options: [
          "A. Yerekeye ibyapa",
          "B. Yerekeye gutambuka mbere",
          "C. Ntagisubizo cy'ukuri kirimo",
          "D. Yerekeye ibimenyetso byo mu muhanda",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "6. Za rumoruki zigira amatara yateganyirijwe ibinyabiziga bizikurura iyo:",
        options: [
          "A. Zifite ubugali burengeje metero 2 na santimetero 10",
          "B. Zifite uburebure burenga metero 6",
          "C. Imbogamizi itewe na zo idatuma amatara yazo atabona neza",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "7. Abanyamaguru ntibashobora gutinda cyangwa guhagarara mu muhanda keretse:",
        options: [
          "A. Nta kinyabiziga kigenda",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Ari mu myanya yabagenewe",
          "D. Ibimenyetso by'umuriro bibibemerera",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "8. Ibinyabiziga bikururwa n'inyamanswa bihererekanijwe mu ubutumwa bigomba kugabanywamo amatsinda afite uburebure butarengeje:",
        options: [
          "A. Metero 300",
          "B. Metero 500",
          "C. Metero 100",
          "D. Metero 30",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "9. Amatara ndanga atuma ikinyabiziga kigaragara mu ntera ikurikira:",
        options: [
          "A. Metero 200",
          "B. Metero 300",
          "C. Metero 150",
          "D. Metero 100",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "10. Umuvuduko ntarengwa w'ibinyabiziga bikururana birenze bitatu:",
        options: [
          "A. Km 25 mu isaha",
          "B. Km 5 mu isaha",
          "C. Km 20 mu isaha",
          "D. Km 15 mu isaha",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "11. Ahari hejuru cyane h'ubuso bumurika bw'amatara magufi ntibushobora kuba aharenze:",
        options: [
          "A. Metero 1,90",
          "B. Metero 1,20",
          "C. Metero 1,55",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "12. Ibyapa ndanga bishyirwa aho biboneye kurushaho ukurikijwe:",
        options: [
          "A. Aho abagenzi bireba bagana",
          "B. Uko birushije kubonwa neza n'abo byagenewe",
          "C. Ubwinshi bw'ibinyabiziga",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "13. Ku matara ijambo ubuso bubonesha risobanura ubuso:",
        options: [
          "A. Burabagiranamo urumuli",
          "B. Bubonesha",
          "C. Busohokana urumuli",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "14. Amategeko y'ihariye yo kugenda mu byambu (ubwato) no ku bibuga by'indege atihutirwa amara igihe gikurikira:",
        options: [
          "A. Kitarenze amezi 3",
          "B. Kitarenze iminsi 30",
          "C. Kitarenze amezi 6",
          "D. Kitarenze amezi atandatu",
        ],
        correctAnswerIndex: 0,
      },
      {
        text: "15. Amatara ya kamenabihu ashobora gusimburwa n'amatara akurikira:",
        options: [
          "A. Yo kubisikana",
          "B. Y'urugendo",
          "C. A na B ni ibisubizo by'ukuri",
          "D. Ndanga",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "16. Igice cy'imizigo kirenga ku mpera y'inyuma y'ikinyabiziga ntikirenza:",
        options: [
          "A. Metero 1",
          "B. Metero 3",
          "C. Metero 2,10",
          "D. Metero 2,70",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "17. Hashyirwaho umuherekeza wunganira umuyobozi w'inyamanswa zikurura ikinyabiziga iyo umubare wazo:",
        options: [
          "A. Urenze enye",
          "B. Urenze eshanu",
          "C. Urenze eshatu",
          "D. Urenze ebyiri",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "18. Igice gikikijwe n'uduce tugali dutandukanye tw'ibara ryera kinyurwamo bikurikira:",
        options: [
          "A. Amagare na velomoteri",
          "B. B na C ni ibisubizo by'ukuri",
          "C. Ibinyabiziga bigenda buhoro",
          "D. Ibinyabiziga bitwarira abantu hamwe",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "19. Igice cy'imizigo yikorewe n'amagare na velomoteri kirenga ku impera y'inyuma ntibushobora kurenza:",
        options: ["A. Cm 40", "B. M 1", "C. Cm 50", "D. M 3"],
        correctAnswerIndex: 2,
      },
      {
        text: "20. Iyo ikinyabiziga cyikoreye ibintu birebire cyane bidashobora kugabanywamo ibice, icyogihe imizigo ntishobora kurenza kumpera y'inyuma y'ikinyabiziga ho:",
        options: [
          "A. Metero 2",
          "B. Metero 3",
          "C. Metero 2,10",
          "D. Metero 1,50",
        ],
        correctAnswerIndex: 2,
      },
    ],
  },
  {
    examNumber: 3,
    title: "Igice cya 3",
    isFree: false,
    questions: [
      {
        text: "1. Umubare w'inyamanswa zikurura ikinyabiziga ntushobora kurenga:",
        options: [
          "A. Eshatu zikurikiranye n'enye zibangikanye",
          "B. Enye ikurikiranya n'eshatu zibangikanye",
          "C. Ebyiri zibangikanye n'enye zikurikiranye",
          "D. Eshatu zikurikiranye n'ebyiri zibangikanye",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "2. Umuvuduko ntarengwa wa velomoteri mu gahanda k’amagare ni:",
        options: [
          "A. Km 50 mu isaha",
          "B. Km 40 mu isaha",
          "C. Km 25 mu isaha",
          "D. Km 60 mu isaha",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "3. Ubugari bw'ikinyabiziga bupimiwe ku butambike ubwo ari bwo bwose ntiburenga:",
        options: [
          "A. Metero 2,50",
          "B. Metero 2,65",
          "C. Metero 3",
          "D. Metero 2,10",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "4. Abanyamaguru batatanye cyangwa bari mu dutsiko batagamije gahunda imwe banyura mu muhanda cyangwa mu gahanda k'amagare iyo:",
        options: [
          "A. Nta tuyira to ku mpande z'umuhanda duhari cyangwa zitagendeka",
          "B. Nta nkengero y'umuhanda iringaniye ihari",
          "C. Nta nkengero yegutse ihari cyangwa butagendeka",
          "D. Nta butaka butsindagiye buhari cyangwa butagendeka",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "5. Inyamanswa zigomba kuyoborwa ku inkombe:",
        options: [
          "A. Y'ibumoso",
          "B. Y'iburyo",
          "C. Y'iburyo cyangwa ibumoso",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "6. Amatara ashakisha acanwa:",
        options: [
          "A. Bidashoboka kubona muri metero 100",
          "B. Iyo ari ngombwa kandi bitabangamiye abandi bayobozi",
          "C. Bidashoboka kubona muri metero 200",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "7. Kimwe mu binyabiziga bikurikira ntibishobora gukurura rumoruki n'imwe:",
        options: [
          "A. Ipikipiki idafite akanyabiziga kuruhande",
          "B. Ipikipiki ifite akanyabaziga kuruhande",
          "C. Velomoteri",
          "D. Igare",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "8. Utugarura rumuri turi mu mbavu z'ikinyabiziga tugomba gusa:",
        options: [
          "A. Umweru",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Umutuku",
          "D. Icyatsi kibisi",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "9. Ku mateme hagati y'ibinyabiziga bifite ibimenyetso byerekana umuvuduko hagomba kubamo intera ya:",
        options: ["A. Metero 3", "B. Metero 10", "C. Metero 2", "D. Metero 5"],
        correctAnswerIndex: 1,
      },
      {
        text: "10. Imikorere y'imyasa ry'amatara ndangacyerekezo rigomba kuba inshuro:",
        options: [
          "A. 100 mu munota",
          "B. 90 mu munota",
          "C. 85 mu munota",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "11. Imyanya ibinyabiziga bigomba guhagararamo ishobora kugaragazwa:",
        options: [
          "A. N'imirongo yera irombereje",
          "B. N'imirongo y'umuhondo yambukiranya umuhanda",
          "C. N'imiringo yera yambukiranya umuhanda",
          "D. N'umurongo mugali wera udacagaguye uciye ku umuhanda",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "12. Uburemere ntarengwa bwa rumoruki feri yayo y'urugendo ishobora gukoreshwa gusa n'uburemere ni:",
        options: ["A. Kg 750", "B. Kg 3500", "C. Kg 3000", "D. Kg 1500"],
        correctAnswerIndex: 1,
      },
      {
        text: "13. Iyo uburebure bw'imizigo iri ku kanyamizigo gakururwa (gakururwa n'inyamanswa) burenga metero 12:",
        options: [
          "A. Umuyobozi agomba gukurura icyo kinyabiziga ku maguru",
          "B. Hagomba umuherekeza ukurikira icyo kinyabiziga ku maguru",
          "C. Hashyirwaho ibimenyetso bigaragaza iyo mizigo",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "14. Birabujijwe gutwara ku ntebe y'imbere y'imodoka abana badafite:",
        options: [
          "A. Imyaka 7",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Imyaka 10",
          "D. Ingingo ya 16",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "15. Igice gikikijwe n'uduce tugali dufite umweru tw'ibara kinyurwamo n'ibinyabiziga bikurukira:",
        options: [
          "A. Amagare na velomoteri z'imitende 2",
          "B. B na C ni ibisubizo by'ukuri",
          "C. Ibinyabiziga bigenda buhoro",
          "D. Ibinyabiziga bitwarira abantu hamwe",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "16. Ikizirikanyije ibinyabiziga bikururana kigomba kugaragazwa, iyo hagati y'uruhande rw'imbere rwa rumoruki n'uruhande rw'inyuma rw'ikinyabiziga gikurura hari umwanya ukurikira:",
        options: [
          "A. Urenze metero imwe",
          "B. Urenze metero eshatu",
          "C. Utarenze metero imwe",
          "D. Utarenze metero eshatu",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "17. Ibimenyetso bikoreshwa berekana impera y'inyuma y'imizigo bishyirwa ku buhagarike bukurikira:",
        options: [
          "A. Hagati ya cm 80 na cm 110",
          "B. Butarenze m 1,55",
          "C. Butarenze m 1,50",
          "D. Butarenze m 1,25",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "18. Amatara maremare amurika mu ntera ya:",
        options: [
          "A. Metero 300",
          "B. Metero 100",
          "C. Metero 200",
          "D. Metero 150",
        ],
        correctAnswerIndex: 2,
      },
      {
        text: "19. Umuyobozi w'imodoka agomba kugira aho yicara hafite ubugari bwa:",
        options: [
          "A. Cm 50",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Cm 60",
          "D. Cm 40",
        ],
        correctAnswerIndex: 1,
      },
      {
        text: "20. Bamwe mu bakurikira ntibabarirwa mu bakozi babifite ububasha:",
        options: [
          "A. Abagenza cyaha n'abakozi bo muri gasutamo",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Abapolisi bo mu mutwe ushinzwe umutekano wo mu muhanda",
          "D. Abofisiye ba polisi y'ingabo",
        ],
        correctAnswerIndex: 1,
      },
    ],
  },
];

export const exercisesToSeed = [
  {
    exerciseNumber: 1,
    title: "imyitozo 1",
    isFree: true,
    questions: [
      {
        text: "1. Iyo banyuze hafi y'inkomyi abanyamaguru bagomba gukikira banyuze mumuhanda abayobozi bagomba gusiga umwanya ufite ubugari bukurikira",
        options: [
          "A. Butarenze metero imwe hagati y'abo n'inkomyi",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Bwa metero imwe hagati y'abo n'inkomyi",
          "D. Butageze kuri metero imwe hagati y'abo n'inkomyi",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "2. Iyo umuhanda ugabanyijwemo ibisate bitatu kandi ukaba ugendwamo mubyerekezo byombi, umuyobozi wese abujijwe kugendera:",
        options: [
          "A. Mugisate cy'ibumoso",
          "B. Mugisate cy'iburyo",
          "C. Mugisate cy'ibumoso cyeretse kujya muri urwo ruhande byemewe",
          "D. Mugisate cyegereye inkombe y'ibumoso bw'umuhanda",
        ],
        correctAnswerIndex: 3,
        hint: "no hint yet",
      },
      {
        text: "3. Ikimenyetso gitanzwe mbere yo gukata kigomba gukomeza kwerekanwa:",
        options: [
          "A. Mugihe ikinyabiziga kikiyoborwa",
          "B. Kugeza gukata birangiye",
          "C. Kugeza kujya k'uruhande birangiye",
          "D. A na B n'ibisubizo by'ukuri",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "4. Kugirango babe umutekano mumuhanda unyura muntara nyinshi icyemezo gifatwa:",
        options: [
          "A. N'umukuru w'intara",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Na minisitiri w'abakozi ba leta",
          "D. Numuyobozi mukuru wa polisi",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "5. Iyo ari ukugenda kumirongo ibangikanye, umuyobozi ashobora gukatira iburyo aruko ari:",
        options: [
          "A. Mumurongo w'ubumoso",
          "B. A na B n'ibisubizo by'ukuri",
          "C. Mumurongo w'iburyo",
          "D. Mumurongo w'uburyo cyangwa w'ubumoso",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "6. Ijambo inzira y'ibinyabiziga risobanura:",
        options: [
          "A. Ahanyurwa n'ibinyabiziga",
          "B. Umuhanda n'inzira ziwukikije",
          "C. Umuhanda n'inkengero zegutse",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "7. Ukuboko kuzamuwe n'umukozi ubifitiye ububasha gutegeka abagenzi bose guhagarara keretse:",
        options: [
          "A. Abataragera mu isangano",
          "B. Abari hafi y'isangano",
          "C. Abageze mu isangano",
          "D. Abatwaye ibinyabiziga ndakumirwa",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "8. Umuyobozi wese ugeze mu isangano aho ibinyabiziga biyoborwa n'ibimenyetso by'umuriro agomba:",
        options: [
          "A. Guhita ava muri iryo sangano",
          "B. Kwitonda",
          "C. Kubahiriza ibyo bimenyetso",
          "D. Kugabanya umuvuduko",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "9. Uruhushya rw'agateganyo rwo gutwara ibinyabiziga rugira agaciro:",
        options: [
          "A. Kunzego zose uretse C,D na E",
          "B. Kunzego A na B",
          "C. Kunzego zose zibinyabiziga",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "10. Abayobozi batambuka mbere mu isangano bagendamo bazengurutse ni:",
        options: [
          "A. Abarigezemo mbere",
          "B. Abaturutse mu kuboko kw'iburyo",
          "C. Abatwaye ibinyabiziga ndakumirwa",
          "D. Abatwaye ibinyabiziga bya gisirikare",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "11. Iyo igenda munzira nyabagendwa, imikumbi igomba kugabanywamo udutsiko tugizwe n'inyamanswa:",
        options: [
          "A. Zitarenze umunani kandi dutandukanijwe n'intera ya metero makumyabiri",
          "B. Zitarenze icumi kandi dutandukanyijwe n'intera ya metero icumi",
          "C. Zitarenze makumyabiri kandi dutandukanyijwe n'intera ya metero icumi",
          "D. Zitarenze icumi kandi dutandukanyijwe n'intera ya metero",
        ],
        correctAnswerIndex: 3,
        hint: "no hint yet",
      },
      {
        text: "12. Iyo bibaye ngombwa ko ibinyabiziga by'iminyururu binyuzwa ku inzira nyabagendwa:",
        options: [
          "A. Bishyirwaho ibyangombwa bituma bitangiza umuhanda",
          "B. Ntibigomba kurenza umuvuduko wa km 25 mu isaha",
          "C. Abayobozi bagomba kubiyobora bitonze",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "13. Umurambararo w'ibyapa bibuza n'ibitegeka bikoreshwa mukugaragaza imirimo ikorerwa mumuhanda ni:",
        options: [
          "A. Cm 90",
          "B. Cm 50",
          "C. Ntagisubizo cy'ukuri kirimo",
          "D. Cm 75",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "14. Uruzitiro rukoreshwa mukugaragaza ahakorerwa imirimo munzira nyabagendwa rugomba gushyirwa ku ubuhagarike buri hagati ya:",
        options: [
          "A. Metero 1,50 na metero 2,10",
          "B. Metero 1 na metero 1,50",
          "C. Ntagisubizo cy'ukuri kirimo",
          "D. Metero 1,25 na metero 1,50",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "15. Uturanga cyerekezo dutoranya tw'ibara ryera dushyirwa:",
        options: [
          "A. Hafi neza y'ahantu habi",
          "B. Mu masangano",
          "C. Hafi y'amasangano",
          "D. Hafi y'ikorosi",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "16. Umurongo uciyemo uduce umenyesha ko umurongo ukomeza wegereje ushobora kuzuzwa:",
        options: [
          "A. N'ibimenyetso by'umuriro",
          "B. N'ibyapa by'inyongera bifite ishusho y'urukiramende",
          "C. N'uturangagukata tw'ibara ryera",
          "D. N'imirongo yambukiranya",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "17. Aho ibinyabiziga bitwarira abantu muri rusange bihagarara ahabujijwe guhagarara igihe kirekire hashobora kugaragazwa n'ibishushanyo",
        options: [
          "A. By'ibara ryera",
          "B. By'ibara risa n'icunga rihishije",
          "C. Ntagisubizo cy'ukuri kirimo",
          "D. By'ibara ry'umuhondo",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "18. Ibimenyetso by'inkomyi bishyirwaho:",
        options: [
          "A. Na polisi y'igihugu",
          "B. A na C ni ibisubizo by'ukuri",
          "C. N'uwayiteye",
          "D. N'ubutegetsi bushinzwe inzira nyabagendwa",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "19. Utubendera dutukura twerekana ahakorerwa imirimo mumuhanda tugomba kugira uruhande rwa:",
        options: ["A. Cm 75", "B. Cm 50", "C. Cm 40", "D. Cm 15"],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "20. Amatara ashyirwa ahari inkomyi n'imirimo hagati ya nimugoroba no mugitondo ogohe ijuru rikeye agomba kuboneka muntera ya:",
        options: [
          "A. Metero 150",
          "B. Metero 100",
          "C. Metero 125",
          "D. Metero 0.75",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
    ],
  },
  {
    exerciseNumber: 2,
    title: "imyitozo 2",
    isFree: false,
    questions: [
      {
        text: "1. Mirongo yera yambukiranya umuhanda igomba kugira ubugari hagati ya:",
        options: [
          "A. Santimetero 25 na santimetero 50",
          "B. Santimetero 40 na santimetero 60",
          "C. Santimetero 20 na santimetero 60",
          "D. Santimetero 10 na santimetero 15",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "2. Impande za kare zera zigomba kugira umubyimba uri hagati:",
        options: [
          "A. Santimetero 40 na santimetero 60",
          "B. Santimetero 25 na santimetero 50",
          "C. Santimetero 10 na santimetero 15",
          "D. Santimetero 20 na santimetero 60",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "3. Ahanyurwa n'abayobozi b'amagare na velomoteri zifite imitende 2 bambukiranya imihanda haciye imirongo 2 icagaguye igizwe na:",
        options: [
          "A. Kare na mpandeshatu z'ibara ry'umuhondo",
          "B. Kare na mpandeshatu z'ibara ryera",
          "C. Kare n'ingirwamwashi z'ibara ry'umuhondo",
          "D. Kare n'ingirwamwashi z'ibara ryera",
        ],
        correctAnswerIndex: 3,
        hint: "no hint yet",
      },
      {
        text: "4. Umurongo mugali wera udacagaguye uciye ku buryo bugororotse ku nkengero y'umuhanda werekana",
        options: [
          "A. Aho abayobozi bagomba guhagarara akanya gato gategetswe",
          "B. Inkombe mpimbano",
          "C. Aho abayobozi bagomba guhagarara akanya gato iyo ari ngombwa",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "5. Imirongo yera irombereje idacagaguye n'icagaguye ishobora gusimburwa n'ibimenyetso by'agateganyo bigizwe:",
        options: [
          "A. N'ibyapa byo ku umuhanda",
          "B. N'imitemeri isa n'icunga rihishije",
          "C. N'imitemeri isa n'umuhondo",
          "D. A na B ni ibisubizo by'ukuri",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "6. Uburebure n'ubutandukane by'uduce tw'umurongo ucagaguye buba bukurikiranye hagati ya:",
        options: [
          "A. Metero 1 na metero 5 no hagati ya metero 3 na metero 15",
          "B. Metero 1 na metero 5 no hagati ya metero 2 na metero 10",
          "C. Metero 2 na metero 5 no hagati ya metero 3 na metero 15",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "7. Umurongo w'umuhondo ucagaguye uciye ku inkombe nyayo y'umuhanda, ku musezero w'inzira y'abanyamaguru cyangwa ku nkengero yegutse usobanura ko:",
        options: [
          "A. Guhagarara umwanya muto n'umunini birabujijwe",
          "B. Guhagarara umwanya munini birabujijwe",
          "C. A na B ni ibisubizo by'ukuri",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "8. Igice cy'inzira nyabagendwa kigarukira kumirongo ibiri yera icagaguye ibangikanye gifite ubugali budahagije ngo imodoka zitambuke neza kiba ari:",
        options: [
          "A. Inzira y'abanyamaguru",
          "B. Agahanda k'amagare",
          "C. Inzira y'amatungo",
          "D. Inzira y'ibinyabiziga",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "9. Iyo uduce tw'umurongo ari tugufi kandi twegeranye bivugako:",
        options: [
          "A. Ari hafi y'ikorosi",
          "B. Ari hafi y'amasangano",
          "C. Ari hafi y'icyago kidasobanuye ukundi",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 3,
        hint: "no hint yet",
      },
      {
        text: "10. Itara ry'umutuku, iry'umuhondo ritamyasa cyangwa risa nk'icyatsi kibisi ashobora gusimburwa uko akurikirana:",
        options: [
          "A. N'umukozi ubifitiye ububasha",
          "B. N'uturanga cyerekezo dutoranya",
          "C. N'ibyapa byo ku muhanda",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 3,
        hint: "no hint yet",
      },
      {
        text: "11. Ahantu uburyo bwo kugenda mu muhanda bwerekanwa n'ibimenyetso bimurika:",
        options: [
          "A. Ibinyabiziga bishobora kugenda bibangikanye",
          "B. Ibinyabiziga bagomba kugenda buhoro",
          "C. Ibinyabiziga bagomba kugabanya umuvuduko",
          "D. A na B ni ibisubizo by'ukuri",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "12. Umurambararo w'ubuso bumurika bw'amatara y'inyongera yashyiriweho abanyamaguru ni:",
        options: [
          "A. Santimetero 10",
          "B. Santimetero 15",
          "C. Santimetero 20",
          "D. Santimetero 5",
        ],
        correctAnswerIndex: 3,
        hint: "no hint yet",
      },
      {
        text: "13. Kubimenyetso bimurika byo mu buryo bw'amatara abiri itara ritukura n'iry'icyatsi kibisi azima akurikirana:",
        options: [
          "A. Yabanje kwakira rimwe",
          "B. Habanje kwaka itara ritukura",
          "C. Habanje kwaka itara ry'icyatsi kibisi",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "14. Ibimenyetso bimurika byerekana uburyo bwo kugenda mu muhanda bishyirwa:",
        options: [
          "A. Iburyo cyangwa ibumoso bw'umuhanda",
          "B. Hejuru y'umuhanda",
          "C. Ibisubizo byose ni byo",
          "D. Ahantu hose biboneye uburyo bwo kugenda",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "15. Iyo ubugali bw'umuhanda budahagije ngo ibisikana ryorohe abayobozi:",
        options: [
          "A. Abayobozi bagomba kuroherana",
          "B. Ntagisubizo cy'ukuri kirimo",
          "C. Bagomba kugenda buhoro",
          "D. Bagomba guhagara",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "16. Iyo icyerekezo kimwe kireba ishami ry'inzira nyabagendwa mu ntara nyinshi, icyerekezo gifatwa na:",
        options: [
          "A. Minisitiri ushinzwe imirimo ya leta",
          "B. Minisitiri ushinzwe gutwara ibintu n'abantu",
          "C. Umukuru wa polisi y'igihugu",
          "D. Minisitiri w'ubutegetsi bw'igihugu",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "17. Uruhushya rwo gukorera amasiganwa n'indi mikino ku nzira nyabagendwa inyura mu ntara nyinshi rutangwa na:",
        options: [
          "A. Minisitiri w'ubutegetsi bw'igihugu",
          "B. Minisitiri w'umuco na siporo",
          "C. Minisitiri ushinzwe gutwara abantu n'ibintu",
          "D. Minisitiri w'imirimo ya leta",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "18. Uburemere ntarengwa bujya mu cyome[ubwato] bwerekanwa n'ibyapa bishyirwa:",
        options: [
          "A. Iburyo bw'umuhanda",
          "B. Kuri buri nkombe",
          "C. Ibumoso bw'umuhanda",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "19. Inkombe z'inzira nyabagendwa cyangwa z'umuhanda zishobora kugaragazwa:",
        options: [
          "A. N'ibikoresho ngarurarumuri",
          "B. N'ibyapa",
          "C. N'ibimenyetso bimurika",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "20. Ibiranga imikandara yo kwirinda ibyago bigenwa:",
        options: [
          "A. Na Minisitiri ushinzwe gutwara abantu n'ibintu",
          "B. N'abakoze ikinyabiziga",
          "C. Polisi y'igihugu",
          "D. Na Minisitiri w'imirimo ya leta",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
    ],
  },
  {
    exerciseNumber: 3,
    title: "imyitozo 3",
    isFree: false,
    questions: [
      {
        text: "1. Birabujijwe gutwara ku ntebe z'ikinyabiziga umubare w'abantu urenze uwateganyijwe:",
        options: [
          "A. Na polisi y'igihugu",
          "B. Na Minisitiri ushinzwe gutwara abantu n'ibintu",
          "C. N'uwagikoze",
          "D. Na Minisitiri w'imirimo ya leta",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "2. Buri modoka igomba kugira uburyo bwo gusubira inyuma bukoreshwa:",
        options: [
          "A. Imodoka igenda",
          "B. Bicaye ku ntebe y'umuyobozi",
          "C. Imodoka isubira inyuma",
          "D. Umuyobozi yitonze",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "3. Ikibanyabiziga kigomba gushyirwaho icyerekana umuvuduko ntarengwa kiri aho umuyobozi areba ni ikinyabiziga:",
        options: [
          "A. Kirenza umuvuduko wa kilometero 40 mu isaha",
          "B. Kitarenze umuvuduko wa kilometero 40 mu isaha",
          "C. Kirenza umuvuduko wa kilometero 50 mu isaha",
          "D. Kitarenza umuvuduko wa kilometero 60 mu isaha",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "4. Isonga y'impombo yohereza ibyotsi ntishobora koherezwa:",
        options: [
          "A. Iburyo bw'umuhanda",
          "B. Ibumoso bw'umuhanda",
          "C. Ibumoso cyangwa iburyo bw'umuhanda",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "5. Ihoni rya velomoteri rigomba kumvikanira muri:",
        options: [
          "A. Metero 20 nibura",
          "B. Metero 50 nibura",
          "C. Metero 75 nibura",
          "D. Metero 25 nibura",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "6. Itara ryo guhagarara rigomba kwaka iyo:",
        options: [
          "A. Ikinyabiziga gihagaze",
          "B. Ikinyabiziga kigenda",
          "C. Feri y'urugendo ikoreshejwe",
          "D. A na C ni ibisubizo by'ukuri",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "7. Utugarura rumuri turi inyuma ya za rumoroki tugomba gusa n'igishushanyo cya:",
        options: [
          "A. Kare",
          "B. Mpandeshatu",
          "C. Urukiramende",
          "D. Ingirwamwashi",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "8. Amatara ndangacyerekezo ashobora gufatanwa n'amatara akurikira:",
        options: [
          "A. B na C ni ibisubizo by'ukuri",
          "B. Maremare n'amagufi",
          "C. Ndanda",
          "D. Amatara yo guhagarara",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "9. Ijambo rumoruki rikoreshwa kuri rumoruki:",
        options: [
          "A. Zagenewe gukururwa n'ibikamyo",
          "B. Zose",
          "C. Zitarenza kg 750",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "10. Amatara ndanga mubyimba agomba kuba adahumishije kandi agaragarira mu ntera ikurikira:",
        options: [
          "A. Metero 100",
          "B. Metero 200",
          "C. Metero 150",
          "D. Metero 125",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "11. Umuvuduko ntarengwa wa velomoteri hakurikijwe uko yakozwe ni:",
        options: [
          "A. Km 60 mu isaha",
          "B. Km 50 mu isaha",
          "C. Km 40 mu isaha",
          "D. Km 25 mu isaha",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "12. Amategeko ntayegayezwa atihutirwa ashyirwaho n'amateka ya:",
        options: [
          "A. Perezida wa Repubulika",
          "B. Minisitiri wo gutwara abantu n'ibintu",
          "C. Polisi y'igihugu",
          "D. Minisitiri w'ubutegetsi bw'igihugu",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "13. Ikinyabiziga ntigishobora gukurura ibinyabiziga birenze:",
        options: ["A. 3", "B. 2", "C. 4", "D. 5"],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
      {
        text: "14. Iyo akanyamizigo gasunikwa cyangwa ibyo gatwaye bidatuma umuyobozi areba neza:",
        options: [
          "A. Umuyobozi agomba kugakurura",
          "B. Hagomba umuherekeza wunganira umuyobozi",
          "C. Umuyobozi arahagarika",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "15. Ijambo feri y'urugendo bisobanura:",
        options: [
          "A. Feri ikoreshwa iyo ikinyabiziga kigenda",
          "B. Feri ikoreshwa n'ikirenge",
          "C. Uburyo bukoreshwa kugira ngo ikinyabiziga kigende buhoro cyangwa gihagarare",
          "D. Ntagisubizo cy'ukuri kirimo",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "16. Uretse igihe icyapa kibyerekana ukundi, uburemere ntarengwa ku mateme akoze mu inginga z'ibiti no mu mbaho ni:",
        options: ["A. Toni 8", "B. Toni 10", "C. Toni 50", "D. Toni 25"],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "17. Ibinyabiziga ndakumirwa bigomba kugira intabaza zihariye zifite amajwi ateye atya:",
        options: [
          "A. Nkarongoroye",
          "B. Yumvikanira kure",
          "C. A na C ni ibisubizo by’ukuri",
          "D. Y’icengera amatwi",
        ],
        correctAnswerIndex: 2,
        hint: "no hint yet",
      },
      {
        text: "18. Amatara ndanga cyerekezo agaragarira nijoro igihe rikeye mu ntera ikurikira:",
        options: [
          "A. Metero 150",
          "B. Metero 200",
          "C. Metero 100",
          "D. Metero 20",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "19. Ijambo akayira risobanura inzira ifunganye yegenewe abagenzi bakurikira:",
        options: [
          "A. Abanyamaguru n'ibinyabiziga by'ibiziga 2 gusa",
          "B. Abanyamaguru gusa",
          "C. Abanyonzi b'amagare na velomoteri",
          "D. Ntagisubizo cy’ukuri kirimo",
        ],
        correctAnswerIndex: 0,
        hint: "no hint yet",
      },
      {
        text: "20. Ikinyabiziga ntigishobora kugira amatara arenze 2 keretse:",
        options: [
          "A. Ndanga",
          "B. A na C ni ibisubizo by’ukuri",
          "C. Ndanga cyerekezo",
          "D. Ndangamubyimba",
        ],
        correctAnswerIndex: 1,
        hint: "no hint yet",
      },
    ],
  },
];
